### PR TITLE
Set Background Color on Dropdowns

### PR DESCRIPTION
**Pull request by CoolSpy3**
Currently, the background color on dropdown menus is unset. This leads to the background occasionally being white in dark-mode (ex. on the term selection dropdown), making the text in the dropdown hard to read. This PR explicitly sets the background color to the background color variable, fixing this issue.

### CODE REVIEW

**Comment by mia1024** [comment]
Just curious, what OS + browser are you using? We have previously encountered this issue but it seemed to be only reproducible on Firefox on certain Linux distros

**Comment by stuxf** [comment]
image
Bug still seems present for me on chrome + fedora (running gnome), did you test with more than one item in the menu? It seems like the transparent css is overriding the set background

**Comment by CoolSpy3** [comment]
@mia1024 I'm currently running Brave v1.64.113 on Windows 10 (64-bit). I can also reproduce the issue on Chrome v123.0.6312.86 and Firefox 124.0.1.

@stuxf I tested these changes locally and they work for me, although I had some trouble with the database, so I had to add the additional select options manually.

**Comment by CoolSpy3** [comment]
I see what you mean about the transparent tag. I missed that. I'll remove it.

**Comment by mia1024** [comment]
I remember there was a reason why I added the transparent background. I have a faint recollection that it might have something to do with how mobile safari renders it. But having the background color set to bg-0 is probably the more correct behavior.

**Review by stuxf — APPROVED** [review]
looks good, seems to fix issue for linux systems

**Comment by mia1024** [comment]
@CoolSpy3 can you please verify this works at nightly.hyperschedule.io after about 10 minutes (github cache duration)

@stuxf let's not deploy this for the time being so we can test this change actually works across all browsers, especially variants of safari

**Comment by CoolSpy3** [comment]
Confirmed! The bug is fixed for me on all browsers I mentioned above!

**Comment by mia1024** [comment]
@CoolSpy3 we have verified and deployed the change to production site

**Pull request merged**
